### ISSUE TITLE
Distro Linux a utilizar ¿Ubuntu Server 14.04?

### ISSUE THREAD

**Issue by jamj2000** [iesgn/cloud#1]
Hola Alberto y José Domingo,

soy alumno vuestro del curso de Cloud. Estoy mirando distros para trabajar con ellas el tema del cloud. Estoy pensando en Lubuntu 14.04 y Ubuntu Server 14.04. 
¿Cuál recomendáis vosotros?

Otra consulta: ¿Es necesario un mínimo de espacio libre en el disco duro?

Un saludo.

**Comment by albertomolina** [comment]
Hola José Antonio,

En principio no es relevante la distribución a utilizar, aunque dependerá de la opción por la que te decantes para instalar OpenStack. También dependerá de si vas a instalar OpenStack en el sistema anfitrión o vas a hacerlo en máquinas virtuales.

Si instalas OpenStack en el sistema anfitrión, te recomendaríamos utilizar Ubuntu 12.04 o Centos 6.5. Probablemente no tendrás problemas con Ubuntu 14.04 o Lubuntu 14.04, pero no lo hemos probado previamente.

Si instalas OpenStack en MVs cualquier sistema será adecuado.

**Comment by josedom24** [comment]
Comentar que independientemente de la opción escogida: en máquina virtual o física, es necesario que el sistema operativo tenga entorno gráfico, ya que normalmente usaremos el navegador web para trabajar con el cloud.

En cuanto al espacio, con 15 Gb tenemos suficiente, actualmente la instalación que yo tengo ocupa unos 12 Gb y las instancias e imágenes que vamos a usar no van a ocupar excesivo espacio.

Un saludo

**Comment by jamj2000** [comment]
Gracias por las respuestas. 
Probaré con Lubuntu 14.04 que tiene entorno gráfico y consume menos recursos. Ya os cuento.

Un saludo.
