### ISSUE TITLE
Aula para instalación de OpenStack

### ISSUE THREAD

**Issue by angoies** [iesgn/cloud#2]
Hola a todos,

Tenemos en el aula del curso monitores, teclados y ratones para los que se quieran llevar una torre para instalarlo.. 

Lo que no tenemos a mano son latiguillos, tendría que buscarlos, así que si os lleváis cada uno el vuestro mejor..
:-)

Ango

**Comment by josedom24** [comment]
Nosotros también nos podemos llevar unos cuantos latiguillos.
Un saludo
