### ISSUE TITLE
Conectarme al curso

### ISSUE THREAD

**Issue by mariabermejo** [iesgn/cloud#3]
Hola,

Soy una alumna de la UEX, estoy realizando el TFM sobre OpenStack y me gustaría poder asistir a los Webinars, como al que se realiza hoy mismo.

GRacias.

**Comment by josedom24** [comment]
Hola María,

Empezamos a las 17:00 en http://www.youtube.com/watch?v=-NAb8pp5E1g&feature=share

Un saludo
